def app 
pipeline {
    agent any 
    environment {
        DOCKERHUB_CREDENTIALS=credentials('DOCKER_HUB_CREDENTIALS')
    }            
    stages {
        stage('Application Build'){
            steps{
                sh 'cd discovery && mvn clean install'
            }
        }    
        stage('Build image') { 
          steps{
              script{
                  docker.withRegistry('https://registry.hub.docker.com', 'DOCKER_HUB_CREDENTIALS') {
                    app = docker.build("sanket151/discovery:latest","./discovery/")
                    app.push()   
                  }
              }
          }        
       }    
    }
    post{
        cleanup{
            sh 'docker image rm -f sanket151/discovery registry.hub.docker.com/sanket151/discovery' 
        }
    }
}