pipeline {
    agent any
    environment {
        DOCKERHUB_CREDENTIALS=credentials('DOCKER_HUB_CREDENTIALS')
    }
    stages {
        stage('Application Build'){
            steps{
                sh 'cd discovery && mvn clean install'
            }
        }
        stage('docker build and push')
        {
            steps{
                def newApp = docker.build("sanket151/discovery:${env.BUILD_TAG}","-f ./discovery/")
                newApp.push()
            }
        }
    }
    post{
        cleanup{
            sh 'docker image rm discovery'
        }
    }
}