def app 
pipeline {
    agent any             
    stages {
        stage('Application Build'){
            steps{
                sh 'cd discovery && mvn clean install'
            }
        }    
        stage('Build image') { 
          steps{
              script{
                    app = docker.build("sanket151/discovery","-f ./discovery/")    
              }
          }        
       }    
       stage('Push image') {
           steps{
               script{
                    docker.withRegistry('https://registry.hub.docker.com', 'git') {            
                    app.push("${env.BUILD_NUMBER}")            
                    app.push("latest")
               }
              }    
           }
       }
    }
    //post{
    //    cleanup{
    //        sh 'docker image rm sanket151/discovery'
    //    }
    //}
}